apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secretstore-cluster
  labels:
    app: product-catalog
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: product-catalog
            namespace: product-catalog
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: product-catalog
  labels:
    app: product-catalog
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: product-catalog
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product-catalog-secrets-external
  namespace: product-catalog
  labels:
    app: product-catalog
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: product-catalog-secrets
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        db-url: "{{ .dbUrl }}"
        db-username: "{{ .dbUsername }}"
        db-password: "{{ .dbPassword }}"
        jwt-secret: "{{ .jwtSecret }}"
  data:
    - secretKey: dbUrl
      remoteRef:
        key: product-catalog/db-url
    - secretKey: dbUsername
      remoteRef:
        key: product-catalog/db-username
    - secretKey: dbPassword
      remoteRef:
        key: product-catalog/db-password
    - secretKey: jwtSecret
      remoteRef:
        key: product-catalog/jwt-secret
